/*
Code generated by github-terraform-generator; DO NOT EDIT.
Any modifications will be overwritten
*/

package tests

import types "github.com/hashicorp/terraform-plugin-framework/types"

type Coffee struct {
	ID          types.Int64   `tfsdk:"id"`
	Name        types.String  `tfsdk:"name"`
	Teaser      types.String  `tfsdk:"teaser"`
	Description types.String  `tfsdk:"description"`
	Image       types.String  `tfsdk:"image"`
	Ingredients []*Ingredient `tfsdk:"ingredients"`
	Customer    *Customer     `tfsdk:"customer"`
}

type Config struct {
	Host   types.String `tfsdk:"host"`
	Bool   types.Bool   `tfsdk:"bool"`
	Int    types.Int64  `tfsdk:"int"`
	String types.String `tfsdk:"string"`
}

type Ingredient struct {
	ID types.Int64 `tfsdk:"id"`
}

type Customer struct {
	ID   types.Int64  `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}
